import { MedicalOption } from "../medical-option.model";

export const followups5: MedicalOption[] = [
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.1.',
    gewaehlt: 0,
    item: 'Blutkultur, 1 Paar',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 3,
    behandlungskosten: 62.7,
    results: ['Blutkultur wird bebrütet, Ergebnis noch ausstehend']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.2.',
    gewaehlt: 0,
    item: 'Blutkultur, 2 Paare',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 3,
    behandlungskosten: 31.3,
    results: ['Blutkultur wird bebrütet, Ergebnis noch ausstehend']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.3.',
    gewaehlt: 1,
    item: 'Liquor Labor',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 6,
    behandlungskosten: 125.3,
    results: ['917 Leukozyten/µl, 81% neutrophile Granulozyten',
      'Eiweiss 170mg/dl (normal bis 45mg/dl)',
      'Glukose 40mg/dl',
      'Lactat 35mg/dl (normal bis 21mg/dl']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.4.',
    gewaehlt: 1,
    item: 'Urinkultur (Urikult)',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 5,
    behandlungskosten: 77,
    results: ['Urikult wird bebrütet, Ergebnisse ausstehend']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.5.',
    gewaehlt: 1,
    item: 'Gramfärbung Liquor',
    aerztlicheArbeitszeit: 30,
    behandlungszeit: 15,
    behandlungskosten: 20,
    results: ['Nachdem Ihr Kittel durch Ihre Färbeaktionen permanenten Schaden genommen hat und Sie völlig entnervt in der hintersten Ecke des Laborschrankes doch noch etwas Mikroskopieröl gefunden haben erblicken Sie voller Stolz in Ihrem Präparat:',
      '+++ Leukozyten',
      ' Diplokokken extra- und intrazellulär, Gramfärbung nicht sicher beurteilbar']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.6.',
    gewaehlt: 0,
    item: 'Liquor Kultur',
    aerztlicheArbeitszeit: 15,
    behandlungszeit: 15,
    behandlungskosten: 50,
    results: ['Kulturen sind angelegt, die Ergebnisse stehen noch aus']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.7.',
    gewaehlt: 0,
    item: 'HSV-PCR aus Liquor',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 2,
    behandlungskosten: 121,
    results: ['Nachdem Sie voller Elan den Liquor von einem Taxifahrer in das mikrobiologische Labor bringen ließen und auch noch den diensthabenden Arzt mit Engelszungen von der Dringlichkeit der PCR überzeugt haben, erfahren Sie nach 6 Stunden und drei weiteren Telefonaten, dass die HSV 1/2 PCR NEGATIV ausgefallen ist']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.8.',
    gewaehlt: 0,
    item: 'Rachenabstrich',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 5,
    behandlungskosten: 49,
    results: ['Abstrichkulturen angelegt, Ergebnis noch ausstehend']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.9.',
    gewaehlt: 0,
    item: 'Malaria Test',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 2,
    behandlungskosten: 14.2,
    results: ['Ausstrich auf Plasmodien ist negativ', 'Malaria Quick Test ist ebenfalls negativ']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.10.',
    gewaehlt: 1,
    item: 'Röntgen Thorax',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 15,
    behandlungskosten: 50,
    results: ['Bettlunge im Liegen',
      'Herzkonfiguration normal',
      'Rechts perihilär V.a. Infiltrat',
      'Keine Stauung',
      'Keine Ergüsse',
      'Kein Pneumothorax']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.11.',
    gewaehlt: 1,
    item: 'Abdomensonographie',
    aerztlicheArbeitszeit: 20,
    behandlungszeit: 30,
    behandlungskosten: 50,
    results: ['Leberparenchymschaden (V.a. Steatosis hepatitis)',
      'Normalbefunde für Gallenblase und Gallenwege',
      'Splenomegalie 16,5 x 6,0 cm',
      'Beide Nieren normal groß, keine Konkremente, kein Harnstau, Harnblase entleert',
      'Nebennieren beidseits schemenhaft, soweit unauffällig',
      'Keine freie Flüssigkeit intraabdominell',
      'Keine pathologischen LK abgrenzbar']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.12.',
    gewaehlt: 0,
    item: 'Cranielle CT ohne KM',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 15,
    behandlungskosten: 150,
    results: ['Kein Hinweis für frische Blutung oder frische Ischämie',
      'Basale Zisternen und äußere Liquorräume eingeengt bzw. verstrichen',
      'Befund vereinbar mit mäßiggradigem Hirnödem'
    ]
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.13.',
    gewaehlt: 0,
    item: 'Cranielle CT mit KM',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 20,
    behandlungskosten: 180,
    results: ['Kein Hinweis für frische Blutung oder frische Ischämie',
      'Basale Zisternen und äußere Liquorräume eingeengt bzw. verstrichen',
      'Fragliche KM-Anreicherung im Bereich der Meningen',
      'Kein Tumornachweis',
      'Befund vereinbar mit mäßiggradigem Hirnödem bei einer akuten Meningitis']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.14.',
    gewaehlt: 0,
    item: 'CT Abdomen mit KM',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 120,
    behandlungskosten: 300,
    results: ['Splenomegalie',
      'Keine pathologischen RF oder LK',
      'Harnwege unauffällig',
      'Keine Darmpathologien',
      'Kein Aszites',
      'CT-morphologisch kein intraabdomineller oder retroperitonealer Infektionsherd abgrenzbar']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.15.',
    gewaehlt: 0,
    item: 'CT Thorax mit KM',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 15,
    behandlungskosten: 300,
    results: ['Keine Infiltrate',
      'Keine pathologischen LK',
      'Keine Pleuraergüsse',
      'Kein Hinweis für eine Lungenembolie',
      'Kein Hinweis auf eine Aortendissektion',
      'Kein Hinweis für eine pulmonalvenöse Stauung']
  },
  {
    rubrik: 'Weitere Diagnostik',
    code: '4.16.',
    gewaehlt: 1,
    item: 'Neurologisches Konsil',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 30,
    behandlungskosten: 100,
    results: ['Hochgradiger V. a. eine akute Meningitis',
      'Liquordiagnostik sofort durchführen',
      'Empirische Therapie mit Ceftriaxon und Ampicillin i.v. sollte sofort eingeleitet werden',
      'Meldung an das Gesundheitsamt veranlassen',
      'Verlegung in die Uniklinik Regensburg angeregt']
  }
];
