import { MedicalOption } from "../medical-option.model";

export const laboratories5: MedicalOption[] = [
  {
    rubrik: 'Labordiagnostik',
    code: '3.1.',
    gewaehlt: 1,
    item: 'Blutbild',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 2.1,
    results: ['Leukozyten 		13,2 /nL  	(NB 4,8 - 11,8)',
      'Erythrozyten		4,02 /pL	(NB 3,8 – 6,1)',
      'Haemoglobin	16,8 g/dL	(NB 13,3 - 17,7)',
      'Haematokrit		48,7 %		(NB 40 – 50)',
      'MCV			86,4 fL		(NB 80 – 100)',
      'MCH			30,4 pg	(NB 28 – 32)',
      'Thrombozyten	144 /nL	(NB 130 – 440)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.2.',
    gewaehlt: 1,
    item: 'Diff. BB',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 2.9,
    results: ['Basophile	0,1 %	(NB 0,2 – 1,3)',
      'Eosinophile		0,7 %	(NB 0,8 – 6,2)',
      'Lymphozyten	3,1 %	(NB 22,4 – 47,9)',
      'Monozyten		4,4 %	(NB 0,7 – 9,3)',
      'Neutrophile		90,1 %	(NB 41,2 – 70,1)',
      'LUC			2,2 %	(NB 0,0 – 4,7)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.3.',
    gewaehlt: 1,
    item: 'Na+, K+, Glukose',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 3.5,
    results: ['Natrium	142 mmol/L	(NB 135 – 150)',
      'Kalium		3,53 mmol/L	(NB 3,5 – 5,5)',
      'Glukose		134 mg/dL	(NB 60 -100)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.4.',
    gewaehlt: 1,
    item: 'Ca++, Cl-, Phosphat',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 3.9,
    results: ['Calcium++	2,23 mmol/L	(NB 2,03 – 2,60)',
      'Chlorid-	105 mmol/L	(NB 95 – 108)',
      'Phosphat	0,88 mmol/L	(NB 0,87 – 1,45)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.5.',
    gewaehlt: 1,
    item: 'Kreatinin, HST, HSR',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 4.3,
    results: ['Kreatinin i.S.	0,86 mg/dL		(NB 0,50 – 1,10)',
      'Harnstoff		24 mg/dL		(NB 10 – 50)',
      'Harnsäure		6,27 mg/dL		(NB 3,4 – 7,0)',
    ]
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.6.',
    gewaehlt: 1,
    item: 'GOT, GPT, AP, Bilirubin',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 5.7,
    results: ['GOT		17 U/L		(NB < 18)',
      'GPT			38 U/L		(NB < 22)',
      'AP			82 U/L		(NB 60 -170)',
      'Bilirubin (ges.)	0,97 mg/dL		(NB < 1,0)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.7.',
    gewaehlt: 0,
    item: 'Blutsenkung',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 5,
    results: ['Blutsenkung 35/72 mm n.W. (NB <8/20)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.8.',
    gewaehlt: 1,
    item: 'CRP',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 7.2,
    results: ['CRP 312 mg/dl (NB <5)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.9.',
    gewaehlt: 1,
    item: 'CK, LDH',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 4.6,
    results: ['CK 		68 U/L		(NB 10 – 80)',
      'LDH		221 U/L		(NB 120 -240)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.10.',
    gewaehlt: 1,
    item: 'Quick & PTT',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 5,
    results: ['Quick		91 %			(NB > 70)',
      'INR		1,20			(NB 0,9 – 1,15)',
      'PTT		33,9 sec.		(NB 28 – 40) '
    ]
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.11.',
    gewaehlt: 0,
    item: 'Fibrinogen, D-Dimer, AT III',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 22.9,
    results: ['Fibrinogen	625 mg/dL		(NB 180 – 340)',
      'D-Dimer		 1,4 µg/dL		(NB < 0,5)',
      'AT III			61,4 %			(NB 70 -140)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.12.',
    gewaehlt: 1,
    item: 'TSH',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 9,
    results: ['TSH 0,98 mlU/mL (NB 0,45-4,5)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.13.',
    gewaehlt: 1,
    item: 'Urinstix',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 1.2,
    results: ['Dichte		normal',
      'Leukozyten	negativ',
      'Nitrit		negativ',
      'Eiweiß 	+',
      'Glukose	negativ',
      'Keton		+++',
      'Blut		+']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.14.',
    gewaehlt: 1,
    item: 'HbA1c',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 5,
    results: ['HbA1c nicht im Notfalllabor enthalten, Ergebnis steht noch aus']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.15.',
    gewaehlt: 0,
    item: 'Venöse BGA',
    aerztlicheArbeitszeit: 0,
    behandlungszeit: 0.5,
    behandlungskosten: 5.4,
    results: ['pO2 		35 mmHg',
      'pCO2		46 mmHg',
      'pH 		7,31		(NB 7,34 – 7,44)',
      'BE 		- 6,0		(NB –2 – +2)']
  },
  {
    rubrik: 'Labordiagnostik',
    code: '3.16.',
    gewaehlt: 0,
    item: 'Arterielle BGA',
    aerztlicheArbeitszeit: 10,
    behandlungszeit: 10,
    behandlungskosten: 11.4,
    results: ['pO2 		85 mmHg	(NB 84 - 104)',
      'pCO2		29 mmHg	(NB 36 – 44)',
      'pH 		7,31		(NB 7,34 – 7,44)',
      'BE 		- 6,0		(NB –2 – +2)']
  }
];
